name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      registry:
        description: Docker registry
        required: false
        type: string
        default: docker.io
      namespace:
        description: Registry namespace/username
        required: true
        type: string
      image:
        description: Docker image name
        required: true
        type: string
    secrets:
      DH_TOKEN:
        description: Docker registry token
        required: true
    outputs:
      registry:
        description: Docker registry
        value: ${{ jobs.build.outputs.registry }}
      namespace:
        description: Registry namespace/username
        value: ${{ jobs.build.outputs.namespace }}
      image:
        description: Docker image name
        value: ${{ jobs.build.outputs.image }}
      digest:
        description: Image digest
        value: ${{ jobs.build.outputs.digest }}
      tags:
        description: Image tags
        value: ${{ jobs.build.outputs.tags }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      registry: ${{ inputs.registry }}
      namespace: ${{ inputs.namespace }}
      image: ${{ inputs.image }}
      digest: ${{ steps.docker_builder.outputs.digest }}
      tags: ${{ steps.docker_metadata.outputs.tags }}
    steps:
      - name: Docker Metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.namespace }}/${{ inputs.image }},enable=true
          tags: |
            type=ref,event=tag

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.namespace }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Docker Build and Push
        id: docker_builder
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.docker_metadata.outputs.tags }}