name: Docker Image CI
on:
  release:
    types:
      - published
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      registry: docker.io
      namespace: devisberto
      image: mail_trace_viewer
    steps:
      - name: Docker Metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.namespace }}/${{ env.image }},enable=true
          tags: |
            type=ref,event=tag
        
      - name: Docker Hub Login
        id: registry_login
        uses: docker/login-action@v3
        with:
          username: ${{ env.namespace }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Docker Build and Push
        id: docker_builder
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.docker_metadata.outputs.tags }}