name: On-call Provenance

on:
  workflow_dispatch:
    inputs:
      registry:
        description: Docker registry
        required: false
        default: docker.io
        type: string
      namespace:
        description: Registry namespace/username
        required: true
        type: string
      image:
        description: Docker image name
        required: true
        type: string
      digest:
        description: Image digest
        required: true
        type: string
  workflow_call:
    inputs:
      registry:
        description: Docker registry
        required: false
        type: string
        default: docker.io
      namespace:
        description: Registry namespace/username
        required: true
        type: string
      image:
        description: Docker image name
        required: true
        type: string
      digest:
        description: Image digest
        required: true
        type: string
    secrets:
      DH_TOKEN:
        required: true
    outputs:
      registry:
        description: Docker registry
        value: ${{ inputs.registry }}
      namespace:
        description: Registry namespace/username
        value: ${{ inputs.namespace }}
      image:
        description: Docker image name
        value: ${{ inputs.image }}
      digest:
        description: Image digest
        value: ${{ inputs.digest }}

jobs:

  provenance:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    env:
      registry: ${{ inputs.registry }}
      namespace: ${{ inputs.namespace }}
      image: ${{ inputs.image }}
      digest: ${{ inputs.digest }}
    steps:
      - name: Docker Hub Login
        id: registry_login
        uses: docker/login-action@v3
        with:
          username: ${{ env.namespace }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.registry }}/${{ env.namespace }}/${{ env.image }}
          subject-digest: ${{ env.digest }}
          push-to-registry: true

