name: Release Workflow
on:
  release:
    types:
      - published
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      registry: docker.io
      namespace: devisberto
      image: mail_trace_viewer
    secrets:
      DH_TOKEN: ${{ secrets.DH_TOKEN }}