name: Reusable SBOM

on:
  workflow_call:
    inputs:
      namespace:
        description: Registry namespace/username
        required: true
        type: string
      image:
        description: Docker image name
        required: true
        type: string
      tag:
        description: Image tag
        required: true
        type: string
      digest:
        description: Image digest
        required: true
        type: string
      cosign-release:
        description: Cosign release version
        required: false
        default: 'v2.5.3'
        type: string
      syft-release:
        description: Syft release version
        required: false
        default: 'v1.28.0'
        type: string
    secrets:
      DH_TOKEN:
        description: Docker registry token
        required: true
    outputs:
      sbom-path:
        description: Path to generated SBOM file
        value: ${{ jobs.sbom.outputs.sbom-path }}

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      sbom-path: ${{ steps.generate_sbom.outputs.sbom-path }}
    env:
      namespace: ${{ inputs.namespace }}
      image: ${{ inputs.image }}
      digest: ${{ inputs.digest }}
      cosign-release: ${{ inputs['cosign-release'] }}
      syft-release: ${{ inputs['syft-release'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.namespace }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: ${{ env.cosign-release }}

      - name: Install Syft
        env:
          SYFT_VERSION: ${{ env.syft-release }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
          | sh -s -- -v -b /usr/local/bin -d $SYFT_VERSION

      - name: Generate SBOM
        id: generate_sbom
        env:
          IMAGE: ${{ env.namespace }}/${{ env.image }}:${{ inputs.tag }}
        run: |
          syft -o spdx-json $IMAGE >> sbom.spdx.json
          echo "sbom-path=sbom.spdx.json" >> $GITHUB_OUTPUT

      - name: Attest SBOM
        env:
          DIGEST: ${{ env.namespace }}/${{ env.image }}@${{ env.digest }}
        run: |
          cosign attest --type=spdxjson --predicate ./sbom.spdx.json --yes $DIGEST

      - name: Upload SBOM to GitHub
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ inputs.tag }} ./sbom.spdx.json
